# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ember.js Octane Tutorial - Building a complex web application
description: > # this means to ignore newlines until "baseurl:"
  Free Ember.js tutorial for absolute beginners. Build a CRUD application from step by step with the latest Ember.js.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yoember.com" # the base hostname & protocol for your site
twitter_username: zoltan_nz
github_username: zoltan-nz

# Build settings
markdown: kramdown
highlighter: rouge

incremental: true

# Url structure /category-name/title-of-the-post/
permalink: /:categories/:title/

exclude: ['Gemfile', 'Gemfile.lock', 'Readme.md', 'README.md', 'Guardfile', '.asset-cache', '.sass-cache', '.deploy', '.editorconfig', '.gitignore', 'Procfile', '_sass']
include: ['.nojekyll']

sass:
  sass_dir: _sass
  style: compressed

compress_html:
  ignore:
    envs: [development]
#  clippings: all
#  comments: all
#  endings: all
#  blanklines: true
#  profile: true
#  startings: [html, head, body]

####
#  CUSTOM COMPONENTS
####

# Show blog-header
show_header: false

kramdown:
  auto_id_stripping: true
  auto_ids: true
