# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ember.js 2 Tutorial - Building a complex web application
email: zdebre@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Free Ember.js tutorial for absolute beginners. Build a CRUD application from step by step with the latest Ember.js v2.5.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yoember.com" # the base hostname & protocol for your site
twitter_username: zoltan_nz
github_username: zoltan-nz

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

# Url structure /category-name/title-of-the-post/
permalink: /:categories/:title/

exclude: ['Gemfile', 'Gemfile.lock', 'Readme.md', 'Guardfile', '.asset-cache', '.sass-cache', '.deploy', '.editorconfig', '.gitignore', 'Procfile']
include: ['.nojekyll']

assets:
  prefix: "/assets"
  compress:
    js: true
    css: true
  sources:
    - _assets/javascripts
  features:
    liquid: true

compress_html:
  ignore:
    envs: [development]
#  clippings: all
#  comments: all
#  endings: all
#  blanklines: true
#  profile: true
#  startings: [html, head, body]

####
#  CUSTOM COMPONENTS
####

# Show blog-header
show_header: false
